name: DevSecOps Pipeline with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build-test-security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t miapp:ci .

    - name: Run unit tests inside container
      run: docker run --rm miapp:ci pytest

    - name: Security scan (Bandit) inside container
      run: docker run --rm miapp:ci bandit -r .

    - name: Dependency scan (Safety) inside container
      run: docker run --rm miapp:ci safety check

    - name: Lint code (Flake8) inside container
      run: docker run --rm miapp:ci flake8 .